version: "3"

services:

  unifi-controller:
    image: unifi:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unifi-controller
    environment:
      - "UNIFI_JVM_OPTS="
    volumes:
      - unifi_data:/usr/lib/unifi/data:rw
      - unifi_logs:/usr/lib/unifi/logs:rw
      - unifi_run:/usr/lib/unifi/run:rw
    ports:
      - 3478:3478/udp   # Unifi communication port
      - 10001:10001/udp # required for AP discovery
      - 8080:8080       # required for Unifi to function
      - 8081:8081       # Unifi communication port
      - 8443:8443       # Unifi webapp communication port
      - 8843:8843       # Unifi communication port
      - 8880:8880       # Unifi communication port
      - 6789:6789       # for throughput test

volumes:

  unifi_data:

  unifi_logs:

  unifi_run:
